title: Crunchy Development
description: Reflexions on how to make your Swift code more nice, fun and crunchy.
email: olivier@halligon.net
author: Olivier Halligon

baseurl:     ""
url:         "http://alisoftware.github.io"
date_format: "%b %-d, %Y"

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: AliSoftware
bitbucket_username:
stackoverflow_id: 803787
twitter_username: aligatr
google_plus_id:
linkedin_username: olivier-halligon
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post:'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
