title: Crunchy Development
description: Making your Swift code more fun 🎉, magical ✨ and crunchier 👌
email: olivier@halligon.net
author: Olivier Halligon
image: apple-touch-icon-180x180.png

baseurl:     ""
url:         "http://alisoftware.github.io"
date_format: "%b %-d, %Y"

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false
show_social_icons:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: crunchydev

# Social icons
github_username: AliSoftware
bitbucket_username:
stackoverflow_id: 803787
twitter_username: aligatr
google_plus_id:
linkedin_username: olivier-halligon-696b9715
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post:'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter:  rouge
permalink:    pretty
plugins:      [jekyll-paginate, jekyll-redirect-from]
paginate:     5
sass:
  compressed: true
include: [".well-known"]
